// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioProject_WebAPI_HotelListing.DataAccess;

namespace PortfolioProject_WebAPI_HotelListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220707073037_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PortfolioProject_WebAPI_HotelListing.DataModels.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lithuania",
                            ShortName = "LT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Latvia",
                            ShortName = "LTU"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Estonia",
                            ShortName = "EE"
                        });
                });

            modelBuilder.Entity("PortfolioProject_WebAPI_HotelListing.DataModels.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sostinės g. 100",
                            CountryId = 1,
                            Name = "Sostinė",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rigos g. 20",
                            CountryId = 2,
                            Name = "Express Hotel",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Talino g. 5",
                            CountryId = 3,
                            Name = "Riga",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("PortfolioProject_WebAPI_HotelListing.DataModels.Hotel", b =>
                {
                    b.HasOne("PortfolioProject_WebAPI_HotelListing.DataModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
